name: Test DevContainer Environment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and Test DevContainer
      uses: devcontainers/ci@v0.2
      with:
        devcontainer-path: .devcontainer
        postCreateCommand: |
          # 必要に応じてコンテナ内でコマンドを実行
          echo "Testing the environment" > /dev/null

    - name: Set up Goss and dgoss
      run: |
        curl -L https://github.com/goss-org/goss/releases/latest/download/goss-linux-amd64 -o /usr/local/bin/goss
        chmod +rx /usr/local/bin/goss
        
        curl -L https://github.com/goss-org/goss/releases/latest/download/dgoss -o /usr/local/bin/dgoss
        chmod +rx /usr/local/bin/dgoss
          
    - name: Run tests inside container
      run: |
        dgoss run -v $(pwd)/goss.yaml:/goss/goss.yaml dev-test-2
