name: Test DevContainer Environment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Set up Goss and dgoss
      run: |
        curl -L https://github.com/goss-org/goss/releases/latest/download/goss-linux-amd64 -o /usr/local/bin/goss
        chmod +rx /usr/local/bin/goss
        
        curl -L https://github.com/goss-org/goss/releases/latest/download/dgoss -o /usr/local/bin/dgoss
        chmod +rx /usr/local/bin/dgoss
          
    - name: Run tests inside container
      uses: devcontainers/ci@v0.2
      with:
        imageName: ghcr.io/manabeai/judge-env
        runCmd: dgoss run -v $(pwd)/goss.yaml:/goss/goss.yaml judge-env
